# Generated by Django 3.2.9 on 2021-11-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpreview',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
