baseURL: https://favianflores.com/
googleAnalytics: "G-DJ6YYREJ5N"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

deployment:
  targets:
    name: https://favianflores.com/
    URL: s3://personal-website-20230829014705989700000001?region=us-east-1
    cloudFrontDistributionID: E3UMPWD5GTR978

params:
  env: production