baseURL: https://favianflores.net/

enableRobotsTXT: false
buildDrafts: false
buildFuture: true
buildExpired: false

deployment:
  targets:
    name: https://favianflores.net/
    URL: s3://personal-website-20230822231933131900000002?region=us-east-1
    cloudFrontDistributionID: E360S5U4GFYSIX

params:
  env: production
  robotsNoIndex: true