# Generated by Django 3.2.9 on 2021-11-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211108_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='show',
            new_name='showPost',
        ),
        migrations.AddField(
            model_name='post',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='showIcon',
            field=models.BooleanField(default=True),
        ),
    ]
