baseURL: https://favianflores.net/
googleAnalytics: ""
buildDrafts: false
buildFuture: true

deployment:
  targets:
    name: https://favianflores.net/
    URL: s3://favianflores.net?region=us-east-1
    cloudFrontDistributionID: E2D8I1PBRLCXOE
