#-------------------------------
# Hugo Site Settings
title: "Favian Flores"
baseURL: "http://10.10.10.138:1313/"
languageCode: "en-us"
cleanDestinationDir: true
paginate: 7
buildDrafts: true
enableGitInfo: true

minify:
  minifyOutput: true

taxonomies:
  tag: "tags"
  category: "categories"

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "RSS", "JSON"]

highlight:
  codeFences: true
  guessSyntax: true
  noClasses: false

frontmatter:
  date:
  - publishDate
  - date
  - lastmod
  expiryDate:
  - expiryDate
  lastmod:
  - :git
  - lastmod
  - date
  - publishDate
  publishDate:
  - publishDate
  - date

menu:
  #-------------------------------
  # Main Menu Settings
  main:
    - identifier: "home"
      name: "Home"
      url: "/"
      weight: 1

    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 2

    - identifier: "archive"
      name: "Archive"
      url: "/posts/"
      weight: 6

    - parent: "Topics"
      name: "Cloud"
      url: "/categories/cloud/"
      weight: 1

    - parent: "Topics"
      name: "DevOps"
      url: "/categories/devops/"
      weight: 2

    - parent: "Topics"
      name: "Web"
      url: "/categories/web/"
      weight: 3

    - parent: "Topics"
      name: "Programming"
      url: "/categories/programming/"
      weight: 4

  #-------------------------------
  # Footer Menu Settings
#  footer:
#    - identifier: "home"
#      name: "Home"
#      url: "/"
#      weight: 1
#
#    - identifier: "about"
#      name: "About"
#      url: "/about/"
#      weight: 2
#
#    - identifier: "blog"
#      name: "Blog"
#      url: "/posts/"
#      weight: 3
#
#
#params:
#  #-------------------------------
#  # Site Metadata
#  logo: ""
#  description: "Hey! I'm Favian and this is my blog where I write about software development. You can find explainers, how-tos, guides, tips & tricks, and anything else I can think of."
#  color_scheme: "auto" # You can choose auto, light, or dark.
#
#  #-------------------------------
#  # Hero Settings
#  hero:
#    enable: true
#    hero__title: "A Dev With A Blog"
#    hero__description: "Hey! I'm Favian and this is my blog where I write about software development. You can find explainers, how-tos, guides, tips & tricks, and anything else I can think of."
#    hero__image: ""
#
#  #-------------------------------
#  # Blog Section Settings
#  blog:
#    enable: true
#    blog__title: "Latest Posts"
#    blog__description: ""
#
#  #-------------------------------
#  # Videos Section Settings
#  videos:
#    enable: false
#    videos__title: "Latest Videos"
#    videos__description: ""
#
#  #-------------------------------
#  # Tag Section Settings
#  tag:
#    enable: false
#    tag: ".NET" # Highlight a specific tag
#
#  #-------------------------------
#  # Email List
#  mailchimp:
#    enable: false
#    mailchimp__title: "Sign me up!"
#    mailchimp__description: "Enter your email to be notified when there's some fresh new content to read."
#    mailchimp__identifier: "" # Add your MailChimp form identifier.
#    mailchimp__input__text: "Your email address"
#    mailchimp__button__text: "Subscribe"
#    mailchimp__background__image: ""
#
#  #-------------------------------
#  # Footer Settings
#  footer:
#    footer__description: "Thanks for checking out my blog!"
#
#  #-------------------------------
#  # Social Links
#  social:
#    - icon: "twitter"
#      name: "Twitter"
#      link: "https://twitter.com/foflores10"
#
#    - icon: "linkedin"
#      name: "LinkedIn"
#      link: "https://linkedin.com/in/foflores10"
#
#  #-------------------------------
#  # Comment Section (Disqus)
#  disqus:
#    enable: false
#    disqusShortname: "" # Add your shortname for Disqus Comments.
